services:

  postgres:
    image: postgres:17
    container_name: recruitment_postgres

    environment:
      POSTGRES_DB: recruitment_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: panos2000

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: recruitment_backend

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recruitment_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: panos2000

    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: recruitment_frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: